[package]
name = "bmath"
version = "0.2.0"
authors = ["Bradley-Solliday <bms284@cornell.edu"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.19"
num = "0.4.3"
